<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subtitle</name>
   <tag></tag>
   <elementGuidId>3e60e0f1-5cea-4bd8-afd1-eded5dee0565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.lead</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='profile']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d299b7be-d5a2-4e44-917a-1ad002e9696a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lead</value>
      <webElementGuid>462717bd-1bd1-4f56-8c27-5fbae9425624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Under construction.</value>
      <webElementGuid>3c10a7a5-7ae4-4616-92df-e6abb2fe2a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 text-center&quot;]/p[@class=&quot;lead&quot;]</value>
      <webElementGuid>2dd51dc2-0863-4427-a831-c0413f5cb3e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='profile']/div/div/div/p</value>
      <webElementGuid>49e353a8-f10f-4eec-9c68-1116b324aa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d22f60b3-0da5-4919-a3c1-b9675cf53777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Under construction.' or . = 'Under construction.')]</value>
      <webElementGuid>e351d5c4-184a-4118-952f-e180e545bd11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
